name: Feature

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Build feature
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            dir_build: ./build
          - os: macos-latest
            name: mac
            dir_build: ./build
          - os: windows-latest
            name: win
            dir_build: ./build/Release
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build binary
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Release
          ls "${{ matrix.dir_build }}"
